name: Continuous integration

on:
  push:
    branches: [main, develop, serenity, euphoria]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set environment variable
        run: |
          SHORT_SHA_COMMIT=$(git rev-parse --short HEAD) 
          echo COMMIT_TAG=${SHORT_SHA_COMMIT} >> $GITHUB_ENV
          echo REPO_MANIFEST_NAME=gitops >> $GITHUB_ENV
          echo REPO_MANIFEST_URL=github.com/aura-nw/gitops.git >> $GITHUB_ENV
          echo REPO_MANIFEST_BRANCH=master >> $GITHUB_ENV
          echo REPO_MANIFEST_ENV_DEV=./clusters/k8s-dev/horoscope-v2 >> $GITHUB_ENV
          echo REPO_MANIFEST_ENV_MAIN=./clusters/k8s-prod/horoscope-v2 >> $GITHUB_ENV
          echo REPO_MANIFEST_ENV_EUPHORIA=./clusters/k8s-testnet-euphoria/horoscope-v2 >> $GITHUB_ENV
          echo REPO_MANIFEST_ENV_SERENITY=./clusters/k8s-testnet-serenity/horoscope-v2 >> $GITHUB_ENV
      - name: Push image to github registry
        env:
          GITHUB_USERNAME: ${{ github.actor }}
          GITHUB_PASSWORD: ${{ secrets.REGISTRY_TOKEN }}
        run: |
          chmod 777 -R ./ci
          ./ci/build.sh
      - name: Update manifest
        env:
          PERSONAL_ACCESS_TOKEN: ${{ secrets.REGISTRY_PASSWORD }}
        run: |
          ./ci/updateManifest.sh